export const ADD_ATTRIBUTE = 'ADD_ATTRIBUTE';
export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const DELETE_ATTRIBUTE = 'DELETE_ATTRIBUTE';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';